#!python3
#check-ip.py   -   find ip address like x.x.x.x on the clipboards

import pyperclip,re

#Create ipnum regex
ipRegex = re.compile(r'''(
    [0-9]+      #NUM
    (\.)        #Point
    [0-9]+
    (\.)
    [0-9]+
    (\.)
    [0-9]+
)''',re.VERBOSE)

#find matches in clipboards text
text = str(pyperclip.paste())

matches = []
for groups in ipRegex.findall(text):
    matches.append(groups[0])

#copy resules to the clipboard
if len(matches) > 0:
    pyperclip.copy('\n'.join(matches))
    print('copy to clipboard:')
    print('\n'.join(matches))
else:
    print('there is no ipnumber')
